version: "3.8"

services:
  db:
    image: postgres:13.3
    container_name: "todo-database"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - default
    volumes:
      - database_postgres:/var/lib/postgresql/data

  web:
    build: .
    container_name: "todo-rest-apis"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default

volumes:
  database_postgres:

networks:
  default:
    driver: bridge
